### ISSUE TITLE
macで readlink -f が使えない

### ISSUE THREAD

**Issue by hnishi** [yutakatay/dotfiles-mini#1]
非常に参考になりました。公開していただき、ありがとうございます。

macでは、GNU版 readlink でないため、readlink -f が動きませんでした。
以下のように修正すれば mac でも、GNU版 readlink 入れずに、問題なく動きました。
（PR立てられなかったので、issueから失礼します。）

```diff
@@ -19,7 +19,7 @@ link_to_homedir() {
   fi

   local script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
-  local dotdir=$(readlink -f ${script_dir}/..)
+  local dotdir=$(dirname ${script_dir})
   if [[ "$HOME" != "$dotdir" ]];then
     for f in $dotdir/.??*; do
       [[ `basename $f` == ".git" ]] && continue
```

**Comment by yutkat** [comment]
ありがとうございます。修正します。
あと、私まったくMac使わないんで動作確認済みをLinuxだけとREADMEに追記しておきます :bow:

**Comment by yutkat** [comment]
`local dotdir=$(readlink -f ${script_dir}/..)`
ここですが、.bashrcとかが配置されているディレクトリの絶対パスをとりたいんですよね。
（シンボリックリンクが相対パスだとサブディレクトリとかでややこしいことになることが多いので）

`local dotdir=$(dirname ${script_dir})`
これだとスクリプトが置かれているところのディレクトリが相対パスで取得してしまうのでちょっと私の期待する動作とは違い気がしています。

**Comment by hnishi** [comment]
ご回答ありがとうございます。

なるほど、たしかに、シンボリックリンクを使っていると期待している動作と異なりますね。
思いついた方法ですと、以下はどうでしょうか？

```
local script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
local dotdir=$(dirname ${script_dir})
```

pwd の -P オプションで、script_dir をリンクを除いた絶対パスにしています。
ubuntu と mac で動作確認しました。

**Comment by yutkat** [comment]
`pwd -P`
こんなオプションあるんですね。知らなかったです。（というかpwdにオプションという概念があることを認識していなかったです）

確かに想定どおり動きました。コードとqiitaも修正しておきます
ありがとうございます :smile:

**Comment by yutkat** [comment]
https://github.com/yutakatay/dotfiles-mini/commit/e61f949a6b66d64aec7b0d03dc3911ef8b4635ea

**Comment by yutkat** [comment]
https://qiita.com/yutakatay/items/c6c7584d9795799ee164/revisions/6
